### ISSUE TITLE
RFE - support Network and Application load balancers in AWS

### ISSUE THREAD

**Issue by ocdavid** [honeycombio/honeyelb#22] opened 2017-12-10 00:09 UTC
My AWS account has no classic ELBs, only NLBs and ALBs, and honeyelb doesn't seem to see them.

Probably a dupe of #14 - just entering this to be sure.

**Comment by nathanleclaire** [comment] 2017-12-11 00:59
Thanks for the issue! We do intend to support these. Stay tuned (closing as dupe of #14 like you mentioned)

**Closed by nathanleclaire** 2017-12-11 00:59 UTC
